<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>订单修改成功</title>
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/non-responsive.css">
    <style type="text/css">
      body {
        margin: 0px;
        padding: 0px;
      }
      .main {
        width: 735px;
        height: 430px;
      }
      .main .jumbotron {
        height: 100%;
        width: 100%;
      }
      .jumbotron h3 {
        margin-top: 128px;
      }
    </style>
  </head>
  <body>
      <div class="main">
        <div class="jumbotron">
          <h3 class="text-center text-danger"><span class="glyphicon glyphicon-remove-circle"></span> 抱歉，此订单不存在</h3>
          <p class="text-center">请按 F5 刷新页面，重新查找订单</p>
        </div>
      </div>
  </body>
</html>
