<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>呼叫中心系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/non-responsive.css">
    <link rel="stylesheet" type="text/css" href="/css/global.css">
    <link rel="stylesheet" type="text/css" href="/css/product.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><img alt="Logo" src="/img/logo.png"></a>
          <a class="navbar-brand" href="#">呼叫中心</a>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><a href="/status">状态监控</a></li>
            <li><a href="/task">任务管理</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">座席管理</a>
              <ul class="dropdown-menu">
                <li><a href="/user">座席管理</a></li>
                <li><a href="/exten">分机状态</a></li>
              </ul>
            </li>
            <li class="dropdown active">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">项目管理</a>
              <ul class="dropdown-menu">
                <li><a href="/order">订单管理</a></li>
                <li class="disabled"><a href="#">客户资料管理</a></li>
                <li><a href="/product">商品管理</a></li>
                <li><a href="/sound">语音管理</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">通话记录</a>
              <ul class="dropdown-menu">
                <li><a href="/cdr/query">通话记录查询</a></li>
                <li><a href="/cdr/report">通话数据报表</a></li>
              </ul>
            </li>
            <li><a href="/help">帮助文档</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a><img class="img-circle icon" src="/img/<?php echo $user->icon; ?>.png" width="19" height="19"> <?php echo mb_substr($user->name, 0, 8, 'UTF-8'); ?></a></li>
            <li><a id="account" href="/account">我的账户</a></li>
            <li><a href="/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> 退 出</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container box">
      <div>
        <ol class="breadcrumb">
          <li class="active">当前位置:</li>
          <li><a href="#">项目管理</a></li>
          <li class="active">商品编辑</li>
        </ol>
      </div>
      <div style="margin-top:45px">
        <form class="form-horizontal" action="/product/update" method="post">
          <div class="form-group">
            <label class="col-sm-4 control-label">商品名称: </label>
            <div class="col-sm-4">
              <input type="hidden" name="id" value="<?php echo $product['id']; ?>">
              <input type="text" class="form-control input-sm" name="name" value="<?php echo htmlspecialchars($product['name'], ENT_QUOTES); ?>" placeholder="请输入商品名称" minlength="1" required>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-4 control-label">商品价格: </label>
            <div class="col-sm-4">
              <input type="text" class="form-control input-sm" style="color:red;font-weight:bold" name="price" value="<?php echo $product['price']; ?>" placeholder="请输入商品价格" min="1" required>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-4 control-label">商品库存: </label>
            <div class="col-sm-4">
              <input type="text" class="form-control input-sm" name="inventory" value="<?php echo $product['inventory']; ?>" placeholder="请输入商品库存数量" min="1" required>
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-4 control-label">商品备注: </label>
            <div class="col-sm-4">
              <textarea class="form-control input-sm" rows="3" name="remark"><?php echo htmlspecialchars($product['remark'], ENT_QUOTES); ?></textarea>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
              <div class="checkbox">
                <label>
                  <input type="checkbox"> 将商品标记为新品上市
                </label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
              <button type="submit" style="width:80px" class="btn btn-success">保存修改</button>
              <a href="/product" style="margin-left:15px;width:80px" class="btn btn-default">取 消</a>
            </div>
          </div>
        </form>
      </div>
    </div>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        $('li.dropdown').mouseover(function() {   
            $(this).addClass('open');
        }).mouseout(function() {
            $(this).removeClass('open');
        }); 

        $(function () {
            $('#account').popover('show');
        });
    </script>
  </body>
</html>
