<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>呼叫中心系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/non-responsive.css">
    <link rel="stylesheet" type="text/css" href="/css/global.css">
    <link rel="stylesheet" type="text/css" href="/css/user.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><img alt="Logo" src="/img/logo.png"></a>
          <a class="navbar-brand" href="#">呼叫中心</a>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><a href="/status">状态监控</a></li>
            <li><a href="/task">任务管理</a></li>
            <li class="dropdown active">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">座席管理</a>
              <ul class="dropdown-menu">
                <li><a href="/user">座席管理</a></li>
                <li><a href="/exten">分机状态</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">项目管理</a>
              <ul class="dropdown-menu">
                <li><a href="/order">订单管理</a></li>
                <li class="disabled"><a href="#">客户资料管理</a></li>
                <li><a href="/product">商品管理</a></li>
                <li><a href="/sound">语音管理</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">通话记录</a>
              <ul class="dropdown-menu">
                <li><a href="/cdr/query">通话记录查询</a></li>
                <li><a href="/cdr/report">通话数据报表</a></li>
              </ul>
            </li>
            <li><a href="/help">帮助文档</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a><img class="img-circle icon" src="/img/<?php echo $user->icon; ?>.png" width="19" height="19"> <?php echo mb_substr($user->name, 0, 8, 'UTF-8'); ?></a></li>
            <li><a id="account" href="/account">我的账户</a></li>
            <li><a href="/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> 退 出</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container box">
      <div>
        <ol class="breadcrumb">
          <li class="active">当前位置:</li>
          <li><a href="/agent">座席管理</a></li>
          <li class="active">分机状态</li>
        </ol>
      </div>
      <div>
        <table class="table table-condensed table-striped table-hover">
          <thead>
            <tr>
              <th class="td-icon">#</th>
              <th>分机号码</th>
              <th>座席姓名</th>
              <th>分机状态</th>
              <th>客户端 IP 地址</th>
              <th>端 口</th>
              <th>客户端设备名称</th>
            </tr>
          </thead>
          <tbody class="text-muted">
          <?php
          if (is_array($extens)) {
            foreach ($extens as $exten) {
              echo '<tr>',"\n";
              echo '<td class="td-icon"><span class="glyphicon glyphicon-phone-alt"></span> </td>',"\n";
              echo '<td>',$exten['sip_user'],'</td>',"\n";
              echo '<td>',mb_substr($exten['name'], 0, 8, 'UTF-8'),'</td>',"\n";
              echo '<td class="text-default">',"\n";

              if ($exten['ping_status'] == 'Reachable') {
                echo '    <span class="label label-success">已注册</span>',"\n";
              } else if ($exten['ping_status'] == 'Unreachable') {
                echo '    <span class="label label-default">超 时</span>',"\n";
              } else {
                echo '    <span class="label label-default">未注册</span>',"\n";
              }
              
              echo '</td>',"\n";
              echo '<td>',$exten['network_ip'],'</td>',"\n";
              echo '<td>',$exten['network_port'],'</td>',"\n";
              echo '<td>',$exten['user_agent'],'</td>',"\n";
              echo '</tr>',"\n";
            }
          }
            ?>
          </tbody>
        </table>
      </div>
    </div>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        $('li.dropdown').mouseover(function() {   
            $(this).addClass('open');
        }).mouseout(function() {
            $(this).removeClass('open');
        }); 

        $(function () {
            $('#account').popover('show');
        });
    </script>
  </body>
</html>
