<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>呼叫中心系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/non-responsive.css">
    <link rel="stylesheet" type="text/css" href="/css/global.css">
    <link rel="stylesheet" type="text/css" href="/css/sounds.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><img alt="Logo" src="/img/logo.png"></a>
          <a class="navbar-brand" href="#">呼叫中心</a>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><a href="/status">状态监控</a></li>
            <li><a href="/task">任务管理</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">座席管理</a>
              <ul class="dropdown-menu">
                <li><a href="/user">座席管理</a></li>
                <li><a href="/exten">分机状态</a></li>
              </ul>
            </li>
            <li class="dropdown active">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">项目管理</a>
              <ul class="dropdown-menu">
                <li><a href="/order">订单管理</a></li>
                <li class="disabled"><a href="#">客户资料管理</a></li>
                <li><a href="/product">商品管理</a></li>
                <li><a href="/sound">语音管理</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">通话记录</a>
              <ul class="dropdown-menu">
                <li><a href="/cdr/query">通话记录查询</a></li>
                <li><a href="/cdr/report">通话数据报表</a></li>
              </ul>
            </li>
            <li><a href="/help">帮助文档</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a><img class="img-circle icon" src="/img/<?php echo $user->icon; ?>.png" width="19" height="19"> <?php echo mb_substr($user->name, 0, 8, 'UTF-8'); ?></a></li>
            <li><a id="account" href="/account">我的账户</a></li>
            <li><a href="/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> 退 出</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container box">
      <div>
        <ol class="breadcrumb">
          <li class="active">当前位置:</li>
          <li><a href="#">项目管理</a></li>
          <li class="active">语音管理</li>
          <li class="pull-right" style="list-style-type:none" data-toggle="modal" data-target="#myModal"><a class="btn btn-success btn-xs"><span class="glyphicon glyphicon-plus"></span> 上传语音</a></li>
        </ol>
      </div>
      <div>
        <table class="table table-condensed table-striped table-hover">
          <thead>
            <tr>
              <th class="td-icon">#</th>
              <th>语音编号</th>
              <th>语音名称</th>
              <th>备注信息</th>
              <th>审核状态</th>
              <th>上传时间</th>
              <th>语音试听</th>
              <th class="td-edit">删除操作</th>
            </tr>
          </thead>
          <tbody class="text-muted">
          <?php
          if (is_array($sounds)) {
            foreach ($sounds as $sound) {
              echo '<tr>',"\n";
              echo '<td class="td-icon"><span class="glyphicon glyphicon-music"></span> </td>',"\n";
              echo '<td>',$sound['id'],'</td>',"\n";
              echo '<td class="text-muted">',mb_substr($sound['name'], 0, 8, 'utf-8'),'</td>',"\n";
              echo '<td>',mb_substr($sound['remark'], 0, 15, 'utf-8'),'</td>',"\n";
              if ($sound['status'] == -1) {
                echo '<td><span class="label label-danger">不通过</span></td>',"\n";
              } else if ($sound['status'] == 0) {
                echo '<td><span class="label label-warning">待审核</span></td>',"\n";
              } else if ($sound['status'] == 1) {
                echo '<td><span class="label label-success">已通过</span></td>',"\n";
              }
              echo '<td>',$sound['create_time'],'</td>',"\n";
              echo '<td><a href="javascript:;" style="color:#337ab7" onClick="show(',"'",$sound['file'],"'",')"><span class="glyphicon glyphicon-headphones"></span> 试 听</a></td>',"\n";
              echo '<td class="td-edit"><a class="btn btn-default btn-xs" href="javascript:;" onClick="changeSound(',$sound['id'],')"><span class="glyphicon glyphicon-edit"></span> 编 辑</a></td>',"\n";
              echo '</tr>',"\n";
            }
          }
          ?>
          </tbody>
        </table>
      </div>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">语音上传</h4>
          </div>
          <form class="form-horizontal" action="/sound/create" method="post" enctype="multipart/form-data">
            <div class="modal-body">
              <div id="header" class="form-group">
                <label class="control-label col-sm-2 col-sm-offset-1">语音名称: </label>
                <div class="col-sm-5 form">
                  <input type="text" class="form-control input-sm input_key" style="font-weight:bold" name="name" minlength="1" placeholder="请输入语音名称" required>
                </div>
                <div class="col-sm-4">
                  <p class="help-block">* 语音名称</p>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2 col-sm-offset-1">语音文件: </label>
                <div class="col-sm-5">
                  <input type="file" class="form-control input-sm" name="file" accept="audio/x-wav" required>
                </div>
                <div class="col-sm-4">
                  <p class="help-block">* 语音文件</p>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2 col-sm-offset-1">备注信息: </label>
                <div class="col-sm-5">
                  <input type="text" class="form-control input-sm" name="remark">
                </div>
                <div class="col-sm-4">
                  <p class="help-block">* 语音备注信息</p>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-sm-2 col-sm-offset-1">语音格式:  </label>
                <div class="checkbox col-sm-8" style="color:#999999">
                  语音文件必须是16位,8000Hz,单声道wav格式的音频文件
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <center>
                <input type="hidden" name="action" value="new">
                <button type="submit" class="btn btn-primary">确认上传</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">取 消</button>
              </center>
            </div>
          </form>
        </div>
      </div>
      <script type="text/javascript" src="/js/jquery.min.js"></script>
      <script type="text/javascript" src="/js/bootstrap.min.js"></script>
      <script type="text/javascript" src="/js/vue.min.js"></script>
      <script type="text/javascript" src="/js/vue-resource.min.js"></script>
      <script type="text/javascript" src="/js/layer.js"></script>
      <script type="text/javascript" src="/js/sound.js"></script>
      <script type="text/javascript">
        $('li.dropdown').mouseover(function() {   
            $(this).addClass('open');
        }).mouseout(function() {
            $(this).removeClass('open');
        }); 

        $(function () {
            $('#account').popover('show');
        });

        $(function () {
            $('[data-toggle="popover"]').popover({
                html: true
            });
        })
      </script>
  </body>
</html>
