<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>呼叫中心运营平台</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/non-responsive.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap-theme.css">
    <link rel="stylesheet" type="text/css" href="/css/global.css">
    <link rel="stylesheet" type="text/css" href="/css/status.css">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><img alt="Logo" src="/img/logo.png"></a>
          <a class="navbar-brand" href="#">运营平台</a>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><a href="/company">企业管理</a></li>
            <li><a href="/task">任务监控</a></li>
            <li><a href="/user">账户管理</a></li>
            <li><a href="/agent">座席管理</a></li>
            <li><a href="/sound">语音管理</a></li>
            <li><a href="/service">服务管理</a></li>
            <li class="dropdown active">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> 系统管理
              </a>
              <ul class="dropdown-menu">
                <li><a href="/gateway">中继网关</a></li>
                <li><a href="/status">服务器状态</a></li>
                <li><a href="/logs">日志记录</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a><img class="img-circle icon" src="/img/<?php echo $user->icon; ?>.png" width="19" height="19"> <?php echo $user->name; ?></a></li>
            <li><a href="/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> 退 出</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container box">
      <div>
        <ol class="breadcrumb">
          <li>当前位置:</li>
          <li>系统管理</li>
          <li class="active">服务器状态</li>
          <li class="pull-right" style="margin-right: 8px"><a class="btn btn-default btn-xs" href="/status"><span class="glyphicon glyphicon-repeat"></span> 刷 新</a></li>
        </ol>
      </div>
      <div>
        <table class="table table-hover">
          <tbody>
            <tr>
              <td style="width:100px"><span class="glyphicon glyphicon-flash"></span> <b>运行时间</b></td>
              <td style="width:150px"><?php echo $status['uptime'];?></td>
              <td style="width:100px"><span class="glyphicon glyphicon-time"></span> <b>系统时间</b></td>
              <td><?php echo date('Y-m-d H:i:s');?></td>
            </tr>
            <tr>
              <td><span class="glyphicon glyphicon-copyright-mark"></span> <b>CPU型号</b></td>
              <td colspan="3"><?php echo $status['cpuinfo'];?></td>
            </tr>
            <tr>
              <td><span class="glyphicon glyphicon-expand"></span> <b>操作系统</b></td>
              <td colspan="3"><?php echo $status['uname'];?></td>
            </tr>
            <tr>
              <td><span class="glyphicon glyphicon-dashboard"></span> <b>系统负载</b></td>
              <td colspan="3"><?php echo $status['loadavg'];?></td>
            </tr>
            <tr>
              <td><span class="glyphicon glyphicon-sound-dolby"></span> <b>内存用量</b></td>
              <td colspan="3"><div class="progress">
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $status['memory']['percentage'];?>%">
                    <span> <?php echo $status['memory']['percentage'];?>% </span>
                  </div>
                </div>
              </td>
            </tr>
            <tr>
              <td><span class="glyphicon glyphicon-hdd"></span> <b>硬盘用量</b></td>
              <td colspan="3">
                <div class="progress">
                  <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="55" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo 100 - $status['hard']['percentage'];?>%">
                    <span> <?php echo 100 - $status['hard']['percentage'];?>% </span>
                  </div>
                </div>
              </td>
            </tr>
            <tr>
              <td colspan="4">
                <br>
                <pre><?php echo $status['pbx'];?></pre>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript">
      $('li.dropdown').mouseover(function() {   
        $(this).addClass('open');
      }).mouseout(function() {
        $(this).removeClass('open');
      });
    </script>
  </body>
</html>
