<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>呼叫中心运营平台</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/non-responsive.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap-theme.css">
    <link rel="stylesheet" type="text/css" href="/css/global.css">
    <link rel="stylesheet" type="text/css" href="/css/company.css">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><img alt="Logo" src="/img/logo.png"></a>
          <a class="navbar-brand" href="#">运营平台</a>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/company">企业管理</a></li>
            <li><a href="/task">任务监控</a></li>
            <li><a href="/user">账户管理</a></li>
            <li><a href="/agent">座席管理</a></li>
            <li><a href="/sound">语音管理</a></li>
            <li><a href="/service">服务管理</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> 系统管理
              </a>
              <ul class="dropdown-menu">
                <li><a href="/gateway">中继网关</a></li>
                <li><a href="/status">服务器状态</a></li>
                <li><a href="/logs">日志记录</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a><img class="img-circle icon" src="/img/<?php echo $user->icon; ?>.png" width="19" height="19"> <?php echo $user->name; ?></a></li>
            <li><a href="/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> 退 出</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container box">
      <div>
        <ol class="breadcrumb">
          <li>当前位置:</li>
          <li>企业管理</li>
          <li class="active">创建企业</li>
        </ol>
      </div>
      <div>
        <form class="form-horizontal" action="/company/create" method="post">
          <div class="form-group">
            <label class="control-label col-xs-4 col-sm-4 col-md-4">企业名称: </label>
            <div class="col-xs-3 col-sm-3 col-sm-3">
              <input type="text" class="form-control input-sm" name="name" placeholder="请输入企业名称" required>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <p class="help-block">企业公司名称，不可为空</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-4 col-sm-4 col-md-4">中继帐号: </label>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <input type="text" class="form-control input-sm" name="username" placeholder="请输入SIP中继帐号" required>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <p class="help-block">SIP中继帐号，不可为空</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-4 col-sm-4 col-md-4">中继密码: </label>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <input type="text" class="form-control input-sm" name="password" placeholder="请输入SIP中继密码" required>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <p class="help-block">SIP中继密码，不可为空</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-4 col-sm-4 col-md-4">网关地址: </label>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <input type="text" class="form-control input-sm" name="ipaddr" placeholder="请输入中继网关IP地址" required>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <p class="help-block">中继网关IP地址，不可为空</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-4 col-sm-4 col-md-4">线路并发: </label>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <input type="number" class="form-control input-sm" name="concurrent" min="1" max="500" placeholder="请输入并发数" required>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <p class="help-block">中继线路最大并发数，不可为空</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-4 col-sm-4 col-md-4">计费帐号: </label>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <input type="text" class="form-control input-sm" name="billing" placeholder="请输入计费帐号" required>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <p class="help-block">公司账户计费帐号</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-4 col-sm-4 col-md-4">其他设置: </label>
            <div class="checkbox col-xs-3 col-sm-3 col-md-3">
              <label>
                <input type="checkbox" name="sound_check"> 语音审核
              </label>
              <label style="margin-left:15px">
                <input type="checkbox" name="data_filter"> 数据过滤服务
              </label>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <p class="help-block">语音审核，号码数据过滤</p>
            </div>
          </div>
          <div class="form-group">
            <hr class="nav-hr" style="width:97%">
            <div class="form-submit col-xs-3 col-sm-3 col-md-3 col-xs-offset-4 col-sm-offset-4 col-md-offset-4">
              <button id="query" type="submit" class="btn btn-success" style="width:80px">创建企业</button>
              <a class="btn btn-default" href="/company" style="margin-left:20px;width:80px">取 消</a>
            </div>
          </div>
        </form>
      </div>
    </div>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/layer.js"></script>
    <script type="text/javascript">
      $('li.dropdown').mouseover(function() {   
        $(this).addClass('open');
      }).mouseout(function() {
        $(this).removeClass('open');
      });

      $("#query").click(function(){
        var index = layer.load(2, {shade: [0.7,'#fff'], time: 3000});
      });
    </script>
  </body>
</html>
