install:
	/usr/bin/mkdir -pv /var/www
	/bin/cp -vrf api /var/www
	/bin/cp -vrf libs /var/www
	/bin/cp -vrf module /var/www
	/bin/cp -vrf public /var/www
	/bin/cp -vrf view /var/www
	/bin/cp -vf config.php /var/www
	/bin/cp -vf loader.php /var/www
	/usr/bin/mkdir -pv /var/www/public/record
	/usr/bin/mkdir -pv /var/www/public/sounds
	/usr/bin/chown apache:apache /var/www
