install:
	/usr/bin/mkdir -pv /var/www
	/bin/cp -vrf api /var/www
	/bin/cp -vrf lemon /var/www
	/bin/cp -vrf manage /var/www
	/usr/bin/mkdir -pv /var/www/lemon/record
	/usr/bin/mkdir -pv /var/www/lemon/sounds
	/usr/bin/chown apache:apache /var/www
