<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>呼叫中心运营平台</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/non-responsive.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap-theme.css">
    <link rel="stylesheet" type="text/css" href="/css/global.css">
    <link rel="stylesheet" type="text/css" href="/css/company.css">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><img alt="Logo" src="/img/logo.png"></a>
          <a class="navbar-brand" href="#">运营平台</a>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><a href="/company">企业管理</a></li>
            <li><a href="/task">任务监控</a></li>
            <li><a href="/user">账户管理</a></li>
            <li><a href="/agent">座席管理</a></li>
            <li><a href="/sound">语音管理</a></li>
            <li><a href="/service">服务管理</a></li>
            <li class="dropdown active">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> 系统管理
              </a>
              <ul class="dropdown-menu">
                <li><a href="/gateway">中继网关</a></li>
                <li><a href="/status">服务器状态</a></li>
                <li><a href="/logs">日志记录</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a><img class="img-circle icon" src="/img/<?php echo $user->icon; ?>.png" width="19" height="19"> <?php echo $user->name; ?></a></li>
            <li><a href="/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> 退 出</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container box">
      <div>
        <ol class="breadcrumb">
          <li>当前位置:</li>
          <li>中继网关</li>
          <li class="active">网关编辑</li>
        </ol>
      </div>
      <div>
        <form class="form-horizontal" action="/gateway/update/<?php echo $gateway['company']; ?>" method="post">
          <div class="form-group">
            <label class="control-label col-sm-4">中继名称: </label>
            <div class="col-sm-3">
              <input type="text" class="form-control input-sm" value="trunk.<?php echo $gateway['company']; ?>.gw" disabled>
            </div>
            <div class="col-sm-3">
              <p class="help-block">中继名称,不可修改</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4">所属公司: </label>
            <div class="col-sm-3">
              <select class="form-control input-sm" disabled>
                <?php
                   if ($company != null) {
                     echo '<option>',$company['name'],'</option>';
                   } else {
                     echo '<option>未知公司</option>';
                   }
                ?>
              </select>
            </div>
            <div class="col-sm-3">
              <p class="help-block">中继所属公司，不可修改</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-xs-4 col-sm-4 col-md-4">中继帐号: </label>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <input type="number" class="form-control input-sm" name="username" value="<?php echo $gateway['username']; ?>" placeholder="请输入中继帐号" required>
            </div>
            <div class="col-xs-3 col-sm-3 col-md-3">
              <p class="help-block">中继注册帐号</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4">中继密码: </label>
            <div class="col-sm-3">
              <input type="password" class="form-control input-sm" name="password" value="" placeholder="密码不修改可留空">
            </div>
            <div class="col-sm-3">
              <p class="help-block">中继注册密码</p>
            </div>
          </div>
          <div class="form-group">
            <label class="control-label col-sm-4">网关地址: </label>
            <div class="col-sm-3">
              <input type="text" class="form-control input-sm" name="ipaddr" value="<?php echo $gateway['ip_addr']; ?>" placeholder="请输入网关IP地址" required>
            </div>
            <div class="col-sm-3">
              <p class="help-block">中继网关IP地址</p>
            </div>
          </div>
          <div class="form-group">
            <hr class="nav-hr" style="width:97%">
            <div class="form-submit col-sm-3 col-sm-offset-4">
              <button id="submit" type="submit" class="btn btn-success" style="width:80px">保存修改</button>
              <a class="btn btn-default" href="/gateway" style="margin-left:20px;width:80px">取 消</a>
            </div>
          </div>
        </form>
      </div>
    </div>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/layer.js"></script>
    <script type="text/javascript">
      $('li.dropdown').mouseover(function() {   
        $(this).addClass('open');
      }).mouseout(function() {
        $(this).removeClass('open');
      });

      $("#submit").click(function(){
        var index = layer.load(2, {shade: [0.7,'#fff'], time: 3000});
      });
    </script>
  </body>
</html>
