<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>呼叫中心运营平台</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/non-responsive.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap-theme.css">
    <link rel="stylesheet" type="text/css" href="/css/global.css">
    <link rel="stylesheet" type="text/css" href="/css/sound.css">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><img alt="Logo" src="/img/logo.png"></a>
          <a class="navbar-brand" href="#">运营平台</a>
        </div>
        <div id="navbar">
          <ul class="nav navbar-nav">
            <li><a href="/company">企业管理</a></li>
            <li><a href="/task">任务监控</a></li>
            <li><a href="/user">账户管理</a></li>
            <li><a href="/agent">座席管理</a></li>
            <li class="active"><a href="/sound">语音管理</a></li>
            <li><a href="/service">服务管理</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span> 系统管理
              </a>
              <ul class="dropdown-menu">
                <li><a href="/gateway">中继网关</a></li>
                <li><a href="/status">服务器状态</a></li>
                <li><a href="/logs">日志记录</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a><img class="img-circle icon" src="/img/<?php echo $user->icon; ?>.png" width="19" height="19"> <?php echo $user->name; ?></a></li>
            <li><a href="/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> 退 出</a></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container box">
      <div>
        <ol class="breadcrumb">
          <li>当前位置:</li>
          <li>语音管理</li>
          <li class="active">所有语音</li>
          <li class="pull-right" style="color:#555555"><a class="btn btn-info btn-xs" href="/sound/upload"><span class="glyphicon glyphicon-plus"></span> 上传语音</a></li>
        </ol>
      </div>
      <div>
        <table class="table table-condensed table-striped table-hover">
          <thead>
            <tr>
              <th>#</th>
              <th>语音编号</th>
              <th>语音名称</th>
              <th>所属公司</th>
              <th>审核状态</th>
              <th>上传者</th>
              <th>上传时间</th>
              <th>上传IP地址</th>
              <th>语音审核</th>
              <th class="td-edit">删除操作</th>
              <th class="td-edit">编辑操作</th>
            </tr>
          </thead>
          <tbody class="text-muted">
          <?php
          if ($sounds != null) {
            foreach ($sounds as $sound) {
              echo '<tr>',"\n";
              echo '<td><span class="glyphicon glyphicon-music"></span></td>',"\n";
              echo '<td>',$sound['id'],'</td>',"\n";
              echo '<td>',$sound['name'],'</td>',"\n";

              if ($companys != null && isset($companys[$sound['company']])) {
                echo '<td>',$companys[$sound['company']]['name'],'</td>',"\n";
              } else {
                echo '<td>未知公司</td>',"\n";
              }
              
              if ($sound['status'] == 0) {
                echo '<td><span class="label label-default">未审核</span></td>',"\n";
              } else if ($sound['status'] == 1) {
                echo '<td><span class="label label-success">已通过</span></td>',"\n";
              } else if ($sound['status'] == -1) {
                echo '<td><span class="label label-danger">不通过</span></td>',"\n";
              }
              
              echo '<td>',$sound['operator'],'</td>',"\n";
              echo '<td>',$sound['create_time'],'</td>',"\n";
              echo '<td>',$sound['ip_addr'],'</td>',"\n";
              echo '<td><a href="javascript:;" style="color:#337ab7" onClick="show(',$sound['id'],', ',"'",$sound['file'],"'",')"><span class="glyphicon glyphicon-headphones"></span> 审 核</a></td>',"\n";
              echo '<td class="td-edit"><a class="btn btn-default btn-xs" href="javascript:;" onClick="deleteSound(',$sound['id'],')"><span class="glyphicon glyphicon-trash"></span> 删 除</a></td>',"\n";
              echo '<td class="td-edit"><a class="btn btn-default btn-xs" href="/sound/edit/',$sound['id'],'"><span class="glyphicon glyphicon-edit"></span> 编 辑</a></td>',"\n";
              echo '</tr>',"\n";
            }
          }
          ?>
          </tbody>
        </table>
      </div>
    </div>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/layer.js"></script>
    <script type="text/javascript" src="/js/sound.js"></script>
    <script type="text/javascript">
      $('li.dropdown').mouseover(function() {   
        $(this).addClass('open');
      }).mouseout(function() {
        $(this).removeClass('open');
      });
    </script>
  </body>
</html>
