<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>呼叫中心系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/non-responsive.css">
    <link rel="stylesheet" type="text/css" href="/css/global.css">
    <link rel="stylesheet" type="text/css" href="/css/agent.css">
  </head>
  <body>
    <div class="container work-box">
      <div class="jumbotron" style="padding:20px">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <ul class="nav navbar-nav">
              <li><img src="/img/<?php echo $user->icon;?>.jpg" class="img-circle icon" alt="icon"></li>
              <li><a href="#"><b class="text-primary"><?php echo $user->name;?></b> (<?php echo $user->uid;?>)</a></li>
              <li><a id="status" href="#">座席状态: <span class="glyphicon glyphicon-ok-sign text-success" aria-hidden="true"></span></a></li>
              <li><p class="navbar-text">To live is to change the world  -  Steve Jobs.</p></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#"><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> 我的设置</a></li>
              <li><a href="/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> 退 出</a></li>
            </ul>
          </div>
        </nav>
        <div>
          <ul class="nav nav-tabs">
            <li role="presentation"><a href="/agent/todayOrder">今日订单</a></li>
            <li role="presentation"><a href="/agent/order">所有订单</a></li>
            <li role="presentation" class="active"><a href="/agent/messages">Messages</a></li>
            <li class="pull-right"><button class="btn btn-default btn-xs" style="height:26px;margin-top:6px"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> 写信息</button></li>
          </ul>
        </div>
      </div>
    </div>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/reqwest.min.js"></script>
    <script type="text/javascript" src="/js/layer.js"></script>
    <script type="text/javascript" src="/js/agent.js"></script>
    <script type="text/javascript">
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      });

      var timer = setInterval(function() {
        syncStatus();
      }, 3000);
    </script>
  </body>
</html>
