<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>订单提示信息</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/css/non-responsive.css">
    <link rel="stylesheet" type="text/css" href="/css/global.css">
    <style type="text/css">
      body {
        width: 658px;
        height: 287px;
        min-width: 658px;
        background-color: ##efefef;
      }
      .container {
        width: 658px;
        height: 287px;
        margin-right: 0px;
        margin-left: 0px;
      }

      .jumbotron {
        width: 648px;
        height: 368px;
        padding-top: 70px;
        margin-top: 10px;
        margin-bottom: 0px;
        background-color: #FFF;
        border-width: 3px;
        border-color: #eeeeee;
        border-style: solid;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="jumbotron text-center" style="-moz-border-radius: 15px;-webkit-border-radius:15px;border-radius: 15px;">
        <div class="alert alert-default alert-dismissible fade in" role="alert">
          <h4 style="color:rgba(92, 184, 92, 0.75)"><span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span> Good 添加成功!</h4>
          <p style="font-size: 14px;line-height:28px">订单已经添加成功，请关闭这这个窗口<br><br></p>
        </div>
      </div>
    </div>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
  </body>
</html>
